version: '3.8'

services:
  server-esclave1:
    build:
      context: ./server-esclave1
    networks:
      internal-net:
        ipv4_address: 172.18.0.2
    mem_limit: 1g
    stdin_open: true
    tty: true

  server-esclave2:
    build:
      context: ./server-esclave2
    networks:
      internal-net:
        ipv4_address: 172.18.0.3
    mem_limit: 1g
    stdin_open: true
    tty: true

  server-esclave3:
    build:
      context: ./server-esclave3
    networks:
      internal-net:
        ipv4_address: 172.18.0.4
    mem_limit: 1g
    stdin_open: true
    tty: true

  server-esclave4:
    build:
      context: ./server-esclave4
    networks:
      internal-net:
        ipv4_address: 172.18.0.5
    mem_limit: 1g
    stdin_open: true
    tty: true

networks:
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
